# See: https://github.com/mkdocs/mkdocs/blob/master/docs/user-guide/configuration.md
site_name: BeeHive
site_description: BeeHive is project management system.
site_author: purnendukar
repo_url: https://github.com/purnendukar/BeeHive-backend

nav:
  - Introduction: index.md
  - API:
      - Overview: api/0-overview.md
      - Authentication: api/1-auth.md
      - Plan: api/2-plan.md
      - Project Manager:
          - Project: api/3-project.md
          - Project Status: api/9-project-status.md
          - Project Permission: api/7-project-permission.md
          - Project Role: api/8-project-role.md
          - Project Members: api/4-project-member.md
          - Sprint: api/5-sprint.md
          - Task: api/6-task.md
  - Releases:
      - Changelog: releases.md

theme:
  name: "material"
  features:
    - tabs
    - instant
  palette:
    - scheme: default
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
    - scheme: slate
      primary: teal
      accent: teal
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode

plugins:
  - git-revision-date-localized

copyright: "Copyright © 2021 - 2022 Purnendu Kar"

# directory to output HTML build
site_dir: _docs_html

# Determines if a broken link to a page within the documentation is considered
# a warning or an error (link to a page not listed in the pages setting). Set to
# true to halt processing when a broken link is found, false prints a warning.
strict: true

# Determines the address used when running mkdocs serve.
# Set it to 8001, so that it doesn't conflict with django's 8000 port
dev_addr: "127.0.0.1:8001"

markdown_extensions:
  - admonition
  - markdown.extensions.meta
  - markdown.extensions.admonition
  - markdown.extensions.smarty
  - markdown.extensions.sane_lists
  - markdown.extensions.codehilite:
      guess_lang: false
  - markdown.extensions.toc:
      permalink: true
  - pymdownx.superfences:
      preserve_tabs: true
  - pymdownx.inlinehilite
  - pymdownx.smartsymbols
  - pymdownx.mark
  - pymdownx.magiclink
  - pymdownx.smartsymbols
  - markdown_include.include:
      base_path: docs
